name: publish_to_pages_staging
runs:
  using: composite
  steps:
  - name: Publish to cloudflare pages (staging)
    run: |-
      cd www
      npx wrangler pages publish . --project-name=deriv-binary-bot-pages --branch=staging
      echo "New staging website - http://staging.cf-pages-deriv-binary-bot.deriv.com"
    shell: bash