name: send_slack_notifications
description: Send Slack notifications
inputs:
  SLACK_WEBHOOK_URL:
    description: "Slack webhook URL"
    required: true
  status:
    description: "Job status"
    required: true
  release_type:
    description: "Release type"
    required: true
  version:
    description: "Version"
    required: true
    default: "N/A"
runs:
  using: composite
  steps:
    - name: Send Slack Notification on Success
      env:
        RELEASE_TYPE: ${{ inputs.RELEASE_TYPE }}
        VERSION: ${{ inputs.VERSION }}
        SLACK_WEBHOOK_URL: ${{ inputs.SLACK_WEBHOOK_URL }}
      if: inputs.status == 'success'
      uses: 'deriv-com/shared-actions/.github/actions/send_slack_notification@master'
        with:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          MESSAGE: {{ inputs.RELEASE_TYPE }} Release succeeded for binary-bot with version ${{ inputs.VERSION }}

    - name: Send Slack Notification on Failure
      env:
        RELEASE_TYPE: ${{ inputs.RELEASE_TYPE }}
        VERSION: ${{ inputs.VERSION }}
        SLACK_WEBHOOK_URL: ${{ inputs.SLACK_WEBHOOK_URL }}
      if: inputs.status == 'failure'
      uses: 'deriv-com/shared-actions/.github/actions/send_slack_notification@master'
        with:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          MESSAGE: ${{ inputs.RELEASE_TYPE }} Release failed for binary-bot with version ${{ inputs.VERSION }}
