name: Binary Bot Production Workflow
on:
  push:
    tags:
      - production.*
jobs:
  release_production:
    name: Build, Test and Deploy to Cloudflare Pages
    runs-on: ubuntu-latest
    container:
      image: node:18.16
    outputs:
      RELEASE_VERSION: ${{ steps.extract_version.outputs.RELEASE_VERSION }}
    steps:
    - name: Checkout
      uses: "./.github/actions/git_checkout_from_cache"
    - name: Install Dependencies
      uses: "./.github/actions/npm_install"
    - name: Build
      uses: "./.github/actions/build"
      with:
        GD_API_KEY: ${{ secrets.GD_API_KEY }}
        GD_APP_ID: ${{ secrets.GD_APP_ID }}
        GD_CLIENT_ID: ${{ secrets.GD_CLIENT_ID }}
        TRACKJS_TOKEN: ${{ secrets.TRACKJS_TOKEN }}
    - name: Test
      uses: "./.github/actions/test"
    - name: Versioning
      uses: "./.github/actions/versioning"
      with:
        release_type: production
    - name: Extract version
      id: extract_version
      run: echo "RELEASE_VERSION=${VERSION}" >> $GITHUB_OUTPUT
    - name: Deploy to Cloudflare Pages
      uses: "./.github/actions/publish_to_cf_pages_production"
      with:
        CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
  send_slack_notification:
      if: always()
      needs: [release_production]
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Conclusion
          uses: technote-space/workflow-conclusion-action@v3
        - name: Send Slack Notification
          uses: "./.github/actions/send_slack_notifications"
          with:
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
            status: ${{ env.WORKFLOW_CONCLUSION }}
            release_type: Production
            version: ${{ needs.release_production.outputs.RELEASE_VERSION}}





