name: deriv-com/binary-bot/release-staging
on:
  push:
    branches:
      - master
jobs:
  release_staging:
    name: Build, Test and Deploy to Cloudflare Pages
    environment: Staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: "./.github/actions/setup_node"
        with:
          node-version: "18.x"
      - name: Install Dependencies
        uses: "./.github/actions/npm_install_from_cache"
      - name: Build
        uses: "./.github/actions/build"
        with:
          GD_API_KEY: ${{ secrets.GD_API_KEY }}
          GD_APP_ID: ${{ secrets.GD_APP_ID }}
          GD_CLIENT_ID: ${{ secrets.GD_CLIENT_ID }}
          TRACKJS_TOKEN: ${{ secrets.TRACKJS_TOKEN }}
      - name: Test
        uses: "./.github/actions/test"
      - name: Deploy to Cloudflare Pages
        uses: "./.github/actions/publish_to_cf_pages_staging"
        with:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
