name: deriv-com/binary-bot/test
on:
    push:
        branches:
            - '*'
            - '!master'
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4.1.0
            - name: Compress git objects
              run: git gc
              shell: bash
            - uses: './.github/actions/npm_install_from_cache'
            - uses: './.github/actions/test'
